---
:project:
  :use_exceptions: TRUE
  :use_mocks: FALSE
  :use_test_preprocessor: TRUE
  :use_preprocessor_directives: FALSE
  :use_auxiliary_dependencies: TRUE
  :auto_link_deep_dependencies: TRUE
  :build_root: build
  :release_build: FALSE
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 0.30.0
  :default_tasks:
    - test:all

# :test_build:
#   :use_assembly: FALSE

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :include:
    - src/
  :support:
    - test/support
  :libraries: []

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  # :common: &common_defines []
  # :common: &common_defines
  :test:
    # - *common_defines
    - TEST
    - CRC8_TABLE
    - CRC16_TABLE
    - CRC32_TABLE
  # :test_preprocess:
  #   - *common_defines
  #   - TEST

# LIBRARIES
# These libraries are automatically injected into the build process. Those specified as
# common will be used in all types of builds. Otherwise, libraries can be injected in just
# tests or releases. These options are MERGED with the options in supplemental yaml files.
:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: []
  :test: []
  :release: []

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    # - stdout_pretty_tests_report
    - stdout_gtestlike_tests_report
    - module_generator
    - raw_output_report
    - xml_tests_report
    - command_hooks
    - colour_report
...
